// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadPreset():Promise<main.Preset>;

export function OS():Promise<string>;

export function SavePreset(arg1:main.Preset):Promise<string>;

export function Start(arg1:main.Preset):Promise<void>;

export function Stop():Promise<void>;
