// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadPreset() {
  return window['go']['main']['App']['LoadPreset']();
}

export function OS() {
  return window['go']['main']['App']['OS']();
}

export function SavePreset(arg1) {
  return window['go']['main']['App']['SavePreset'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
